version: "3.8"

services: 
  postgres-db:
    image: postgres:14.4-alpine
    container_name: postgres-db
    environment: 
      - POSTGRES_DB=default
      - MONGO_INITDB_ROOT_PASSWORD=postgres
      - POSTGRES_PASSWORD=password



